/* Shared content for the Namami Law Offices website prototype.
   Plain data — no JSX — loaded before Layout.jsx and page scripts. */

window.NAV = [
  ['index.html', 'Home'],
  ['about.html', 'The Firm'],
  ['team.html', 'Team'],
  ['practice.html', 'Practice Areas'],
  ['insights.html', 'Insights'],
  ['contact.html', 'Contact'],
];

window.PRACTICE_AREAS = [
  {
    slug: 'trademarks',
    name: 'Trademarks',
    oneLiner: 'Clearance, filing, prosecution, enforcement — India and international.',
    intro: 'Trademarks are how the market recognises you. We clear, file, and defend the marks a brand is built on — in India and the jurisdictions that matter to it.',
    handle: [
      'Availability and clearance searches before you commit to a name or mark',
      'Filing and prosecution across the relevant classes, in India and abroad',
      'Responses to examination reports, oppositions, and rectifications',
      'Watch services, coexistence agreements, and renewals',
    ],
    whoFor: 'Founders naming a company or product, D2C brands scaling across categories, and businesses entering new markets.',
    why: [
      'A partner reviews clearance and filing strategy — not a junior team working without oversight.',
      'We think in classes and categories the way your business actually grows, not just the mark in front of us.',
    ],
    services: [
      'Trademark clearance and availability searches',
      'Filing and prosecution — India and international',
      'Opposition and rectification proceedings',
      'Portfolio management and renewals',
      'Enforcement and cease-and-desist actions',
      'Licensing and assignment agreements',
    ],
    faqs: [
      ['How long does trademark registration take in India?', 'Typically 18–24 months if unopposed, though a clean clearance search and accurate classification can prevent most delays.'],
      ['Should I file before or after I launch?', 'Before, where possible. Filing early establishes priority and avoids rebranding costs if a conflict surfaces post-launch.'],
      ['Do I need separate filings for each country?', 'Yes, unless you use a Madrid Protocol application, which lets you designate multiple member countries from a single India-based filing.'],
      ['What happens if someone opposes my application?', 'You respond within the statutory window with evidence of use, distinctiveness, or honest concurrent use. We handle the filing and hearing.'],
    ],
    recognition: 'Recognised for trademark practice, Legal Era 2024.',
  },
  {
    slug: 'copyright-media',
    name: 'Copyright & Media Law',
    oneLiner: 'Protect creative work. License it right. Enforce it fast.',
    intro: 'Copyright exists the moment a work is fixed. We help creators, studios, and platforms establish ownership, license it on the right terms, and act quickly when it is infringed.',
    handle: [
      'Authorship, ownership, and first-owner questions for commissioned work',
      'Assignment and licence drafting that survives format and platform changes',
      'Fair-dealing assessments for criticism, review, reporting, and teaching',
      'Takedowns, infringement notices, and litigation support',
    ],
    whoFor: 'Publishers, production houses, platforms, and individual creators whose business is the work itself.',
    why: [
      'We read contracts the way creative businesses actually operate — across formats, platforms, and territories.',
      'Enforcement moves fast: takedowns and notices go out within days, not weeks.',
    ],
    services: [
      'Copyright registration and portfolio management',
      'Assignment, licence, and work-for-hire agreements',
      'Fair-dealing and permissions review',
      'Infringement notices and takedown coordination',
      'Litigation support and settlement negotiation',
      'Rights audits for publishing and media catalogues',
    ],
    faqs: [
      ['Do I need to register my copyright?', 'No — copyright exists automatically on creation. Registration is optional but strengthens your position as evidence in a dispute.'],
      ['Who owns work I commission from a freelancer?', 'The creator, by default, unless a written assignment transfers ownership to you. Verbal agreements are not enough.'],
      ['Can I use a clip or quote under fair dealing?', 'Sometimes — for criticism, review, reporting, or teaching, within limits. We assess each use against the statutory factors.'],
      ['How fast can you issue a takedown notice?', 'Typically within 2–3 business days of instruction, once ownership and the infringing use are confirmed.'],
    ],
    recognition: 'Panel counsel to independent publishers and OTT platforms on catalogue rights.',
  },
  {
    slug: 'patents',
    name: 'Patents',
    oneLiner: 'Technical IP protection for inventors and innovation-led businesses.',
    intro: 'A patent protects how something works, not how it looks — and public disclosure before filing can destroy novelty. We help inventors file first and demo second.',
    handle: [
      'Patentability assessment and prior-art searching',
      'Drafting specifications and claims with the right scope',
      'Prosecution before the Patent Office and responses to objections',
      'Inventor-assignment and employer-IP advisory for startups and studios',
    ],
    whoFor: 'Deep-tech founders, R&D teams, and manufacturers with a genuinely novel process or product.',
    why: [
      'Claims are drafted for enforceability, not just grant — scope matters more than speed.',
      'We coordinate directly with technical founders, translating invention into defensible claims.',
    ],
    services: [
      'Patentability and prior-art searches',
      'Patent drafting and specification review',
      'Filing and prosecution — India and international (PCT)',
      'Freedom-to-operate (FTO) opinions',
      'Inventor assignment and employer-IP agreements',
      'Patent portfolio strategy and audits',
    ],
    faqs: [
      ['Can I demo my invention before filing?', 'Public disclosure before filing can destroy novelty in most jurisdictions. File first, or use a confidentiality agreement if a demo is unavoidable.'],
      ['What is a freedom-to-operate opinion?', 'An assessment of whether your product infringes existing patents — separate from whether your own invention is patentable.'],
      ['How long does patent grant take in India?', 'Typically 2–4 years from filing to grant, depending on examination request timing and objections raised.'],
      ['Who owns a patent developed by an employee?', 'Governed by the employment contract. We recommend explicit assignment clauses before development begins, not after.'],
    ],
    recognition: 'Advising deep-tech and hardware startups on first-filing strategy.',
  },
  {
    slug: 'designs',
    name: 'Designs',
    oneLiner: 'Visual innovation protected — from product to packaging.',
    intro: 'Design registration covers appearance — lines, contours, ornamentation — and must be new and original at filing. It is fast, cost-effective, and often overlooked.',
    handle: [
      'Design registration for the visual appearance of articles',
      'Strategy across the overlap between design, trademark, and copyright',
      'Enforcement against look-alikes and knock-offs',
      'Portfolio planning for product families and packaging lines',
    ],
    whoFor: 'Product studios, packaging teams, and D2C brands where appearance drives purchase decisions.',
    why: [
      'Design protection is quick to secure — we file ahead of launch, not after a copycat appears.',
      'We plan portfolios across product families, not one registration at a time.',
    ],
    services: [
      'Design registration and prosecution',
      'Design-trademark-copyright overlap strategy',
      'Portfolio planning for product and packaging families',
      'Enforcement against imitation and knock-offs',
      'Design licensing agreements',
    ],
    faqs: [
      ['What qualifies for design registration?', 'The shape, configuration, pattern, or ornamentation of an article — provided it is new and has not been disclosed publicly before filing.'],
      ['How long does design registration last?', 'An initial term of 10 years, renewable once for a further 5 years in India.'],
      ['Can a product be protected by both design and trademark?', 'Yes — design protects appearance at a point in time; trademark can protect a distinctive shape used consistently as a source identifier.'],
      ['What if a competitor copies our packaging?', 'We move quickly on cease-and-desist and, where needed, coordinate enforcement action against the imitation.'],
    ],
    recognition: 'Design portfolio counsel for consumer product and packaging brands.',
  },
  {
    slug: 'ip-enforcement',
    name: 'IP Enforcement',
    oneLiner: 'Cease-and-desist to litigation coordination. We pursue infringers.',
    intro: 'Registration means little without enforcement. We act on infringement quickly and proportionately — from a first notice through litigation coordination.',
    handle: [
      'Cease-and-desist notices and settlement negotiation',
      'Online takedowns across marketplaces and platforms',
      'Litigation coordination with counsel and investigators',
      'Anti-counterfeiting and raid coordination where warranted',
    ],
    whoFor: 'Rights holders facing counterfeiting, brand imitation, or unauthorised use of their IP.',
    why: [
      'We escalate proportionately — a notice first, litigation only where it is the right tool.',
      'A single point of contact coordinates investigators, platforms, and litigation counsel.',
    ],
    services: [
      'Cease-and-desist notices',
      'Online marketplace and platform takedowns',
      'Settlement and coexistence negotiation',
      'Litigation coordination and case strategy',
      'Anti-counterfeiting investigation coordination',
    ],
    faqs: [
      ['What is the first step against an infringer?', 'Usually a cease-and-desist notice — it is fast, establishes a paper trail, and resolves many disputes without litigation.'],
      ['Can you get counterfeit listings taken down?', 'Yes — most marketplaces have IP complaint procedures; we file and follow up until listings are removed.'],
      ['When does a matter go to litigation?', 'When a notice is ignored, the infringement is significant, or an injunction is needed to stop ongoing harm.'],
      ['Do you handle enforcement outside India?', 'We coordinate with a network of associate counsel across the UAE, US, EU, UK, and ASEAN for cross-border matters.'],
    ],
    recognition: 'Enforcement coordination across marketplace, brand, and media disputes.',
  },
  {
    slug: 'strategic-advisory',
    name: 'Strategic Advisory',
    oneLiner: 'Portfolio audits, commercialization, M&A due diligence, retainer counsel.',
    intro: 'IP protection is a means to an end: building value, securing funding, enabling growth. We advise on the commercial side of intellectual property, not just the filing.',
    handle: [
      'IP portfolio audits and valuation support',
      'Licensing and franchise structuring',
      'M&A and investment due diligence on IP assets',
      'Ongoing retainer counsel for founders and in-house teams',
    ],
    whoFor: 'Founders raising capital, businesses licensing their IP, and acquirers conducting diligence.',
    why: [
      'A franchise is, at its core, an IP licensing arrangement — we structure the underlying rights, not just the deal.',
      'We advise before the transaction, so IP strengthens the valuation rather than becoming a diligence flag.',
    ],
    services: [
      'IP portfolio audits',
      'Licensing and franchise agreements',
      'M&A and investment due diligence',
      'IP valuation support',
      'Retainer counsel and quarterly portfolio reviews',
    ],
    faqs: [
      ['What does an IP audit cover?', 'A full inventory of registered and unregistered IP, ownership confirmation, gaps in protection, and a prioritised action plan.'],
      ['Why does IP matter in due diligence?', 'Investors and acquirers verify that IP is properly owned, assigned, and free of conflicting claims before committing capital.'],
      ['How is a licensing royalty structured?', 'Typically a percentage of net revenue with minimum guarantees, though structure depends on the asset, exclusivity, and territory.'],
      ['Do you offer ongoing retainer counsel?', 'Yes — a fixed advisory arrangement covering periodic reviews, quick-turnaround queries, and filing credits.'],
    ],
    recognition: 'Advisory counsel on licensing and portfolio structuring for growth-stage brands.',
  },
  {
    slug: 'employment-labour-creative',
    name: 'Employment & Labour Law in Creative Industries',
    oneLiner: 'Protecting artists, performers, and creative professionals — from contracts to workplace rights.',
    intro: 'Creative work is still work. We advise artists, performers, and the studios that engage them on contracts, compensation, and workplace rights specific to creative industries.',
    handle: [
      'Engagement, production, and performer contracts',
      'Compensation, credit, and royalty terms in employment agreements',
      'Workplace rights and dispute resolution for creative professionals',
      'Statutory compliance for studios and production houses',
    ],
    whoFor: 'Performers, artists, and creative professionals, and the studios and productions that engage them.',
    why: [
      'We read creative-industry contracts for what they are — engagements with rights the statute will not let performers waive.',
      'Advisory sits alongside our IP practice, so contract and rights questions are handled together, not separately.',
    ],
    services: [
      'Performer and artist engagement agreements',
      'Credit, royalty, and compensation structuring',
      'Workplace rights advisory for creative professionals',
      'Dispute resolution and grievance support',
      'Statutory compliance for productions and studios',
    ],
    faqs: [
      ['Can a performer waive their statutory rights in a contract?', 'Not entirely — certain performer rights, including royalty entitlements, are non-waivable under Indian copyright law regardless of contract terms.'],
      ['What should an artist look for in an engagement contract?', 'Clear terms on credit, compensation structure, ownership of the resulting work, and the scope of exclusivity requested.'],
      ['Do freelance creatives have workplace rights?', 'Some protections apply regardless of engagement structure; classification as employee, contractor, or performer affects which ones.'],
      ['Who handles disputes over credit or royalties?', 'We advise directly and, where needed, escalate through the relevant collection society or dispute resolution forum.'],
    ],
    recognition: 'Advisory counsel to independent artists, performers, and production houses.',
  },
];

window.INDUSTRIES = [
  'Technology & SaaS', 'Startups & D2C', 'Media & Entertainment', 'Health & Wellness',
  'Manufacturing', 'Content Creators', 'International Brands entering India', 'Professional Services',
];

window.WHY_NAMAMI = [
  ['Partner-Level Attention', 'Boutique practice. No file numbers, no junior associates running your matter without oversight.'],
  ['Business-First Counsel', 'IP protection is a means to an end: building value, securing funding, enabling growth.'],
  ['Transparent & Accessible', 'No legalese. No billing surprises. Fixed fees, clear timelines, plain language.'],
  ['Modern & Tech-Enabled', 'Structured workflows, real-time tracking, fast turnarounds. We run a tight operation.'],
];

window.TESTIMONIALS = [
  ['Working with Namami Law has been transformative for our brand strategy. They don\u2019t just file trademarks — they think strategically about our entire IP roadmap.', 'Founder, D2C Beauty Brand'],
  ['As a content creator, I needed someone who understood both the legal and creative sides. Namami Law gets it.', 'Digital Content Creator'],
  ['Fast, precise, and transparent. The fixed-fee packages gave us budget certainty. Highly recommend for any startup taking IP seriously.', 'Founder, Health Tech Startup'],
];

window.TEAM = [
  {
    name: 'Rishabh Saxena',
    role: 'Founder & Managing Partner',
    focus: ['Trademarks', 'Copyright', 'Media Law', 'IP Commercialization'],
    bio: 'Rishabh founded Namami Law to give creators and founders the kind of IP counsel usually reserved for large enterprises. His practice spans trademark strategy, copyright and media transactions, and commercialization advisory for growth-stage brands.',
  },
  {
    name: 'Saurabh Vaid',
    role: 'Co-Founder, Patent Practice',
    focus: ['Patents', 'Patentability', 'FTO', 'Portfolio Management'],
    bio: 'Saurabh leads the patent practice, advising deep-tech founders and manufacturers on patentability, freedom-to-operate, and portfolio strategy. He works closely with technical teams to translate invention into defensible claims.',
  },
  {
    name: 'Jannavi Singha',
    role: 'Co-Founder, Trademark Practice',
    focus: ['Clearance', 'Prosecution', 'Enforcement', 'International'],
    bio: 'Jannavi leads trademark clearance, prosecution, and enforcement, with particular depth in international filing strategy for brands expanding beyond India.',
  },
];

window.INSIGHTS = [
  {
    slug: 'trademark-clearance-search',
    title: 'Trademark clearance: the search most founders skip',
    desc: 'Why a clearance search before filing saves far more than it costs — and what it actually checks.',
    type: 'Article',
    practices: ['Trademarks'],
    verticals: ['Startups & D2C'],
    author: 'Jannavi Singha',
    date: '2026-03-14',
    reads: 1240,
    pillar: 'Trademark Essentials',
  },
  {
    slug: 'copyright-ownership-commissioned-work',
    title: 'Copyright ownership when you commission creative work',
    desc: 'The default owner of commissioned work may surprise you — and why a written assignment matters.',
    type: 'Article',
    practices: ['Copyright & Media Law'],
    verticals: ['Content Creators', 'Media & Entertainment'],
    author: 'Rishabh Saxena',
    date: '2026-02-27',
    reads: 980,
    pillar: 'Copyright for Creators',
  },
  {
    slug: 'patent-or-trade-secret',
    title: 'Patent or trade secret: choosing the right protection',
    desc: 'Not every invention should be patented. A framework for deciding which route protects more value.',
    type: 'Article',
    practices: ['Patents'],
    verticals: ['Technology & SaaS'],
    author: 'Saurabh Vaid',
    date: '2026-02-10',
    reads: 760,
    pillar: 'IP for Startups',
  },
  {
    slug: 'design-registration-product-packaging',
    title: 'Design registration for product and packaging teams',
    desc: 'A fast, low-cost protection layer most product teams file too late — or not at all.',
    type: 'Article',
    practices: ['Designs'],
    verticals: ['Manufacturing'],
    author: 'Saurabh Vaid',
    date: '2026-01-22',
    reads: 540,
    pillar: 'IP Strategy & Commercialization',
  },
  {
    slug: 'what-a-cease-and-desist-does',
    title: 'What a cease-and-desist letter actually does',
    desc: 'It is rarely the final word — here is what it accomplishes and what typically follows.',
    type: 'Article',
    practices: ['IP Enforcement'],
    verticals: ['Media & Entertainment'],
    author: 'Rishabh Saxena',
    date: '2026-01-08',
    reads: 890,
    pillar: 'Media & Entertainment Law',
  },
  {
    slug: 'licensing-term-sheet-basics',
    title: 'Licensing your IP: what a term sheet should cover',
    desc: 'Territory, exclusivity, royalty triggers, and reversion — the terms that decide what a licence is worth.',
    type: 'Article',
    practices: ['Strategic Advisory'],
    verticals: ['Startups & D2C'],
    author: 'Rishabh Saxena',
    date: '2025-12-18',
    reads: 610,
    pillar: 'IP Strategy & Commercialization',
  },
  {
    slug: 'on-the-record-performer-rights',
    title: 'On the Record: Protecting Performers\u2019 Rights',
    desc: 'A conversation on royalty entitlements and moral rights performers cannot sign away.',
    type: 'Podcast',
    practices: ['Employment & Labour Law in Creative Industries', 'Copyright & Media Law'],
    verticals: ['Media & Entertainment'],
    author: 'Rishabh Saxena',
    date: '2026-03-01',
    reads: 430,
    pillar: 'Media & Entertainment Law',
  },
  {
    slug: 'filing-season-founders-guide',
    title: 'Filing Season: A Founder\u2019s Guide to Trademarks',
    desc: 'What to prepare before your first trademark filing, in plain conversation.',
    type: 'Podcast',
    practices: ['Trademarks'],
    verticals: ['Startups & D2C'],
    author: 'Jannavi Singha',
    date: '2025-11-30',
    reads: 380,
    pillar: 'Trademark Essentials',
  },
];

window.CONTENT_TYPES = ['Article', 'Podcast', 'Video Explainer', 'Case Study', 'Guide'];
window.CLIENT_VERTICALS = ['Startups & D2C', 'Media & Entertainment', 'Tech & SaaS', 'Fashion', 'Health', 'Manufacturing', 'Content Creators'];
window.AUTHORS = ['Rishabh Saxena', 'Saurabh Vaid', 'Jannavi Singha'];
